version: "3"
services:
  back:
    build:
      context: .
      dockerfile:  docker/gobase.Dockerfile
    env_file: .env
    depends_on:
      - database
  unit-gotest:
    build:
      context: .
      dockerfile: docker/gotest.Dockerfile
    env_file: .env
  golint:
    build:
      context: .
      dockerfile: docker/golint.Dockerfile
    env_file: .env
  database:
    image: mariadb:10.1
    env_file: .env
    hostname: database
    ports:
      - 3306:3306
