version: "3"
services:
  apidocumentation:
    build:
      context: .
      dockerfile: docker/slateserver.Dockerfile
    image: registry.le-corre.eu:5000/innerapi:slate-alpha-doc
    volumes:
      - "./swagger.json:/tmp/swagger"
      # - "./docker_resources/slate_resources:/home/slate"
    ports:
      - 4567:4567
  back:
    build:
      context: .
      dockerfile:  docker/gobase.Dockerfile
    env_file: .env
    image: registry.le-corre.eu:5000/go:base
  goconvey:
    build:
      context: .
      dockerfile: docker/goconvey.Dockerfile
    env_file: .env
    depends_on: 
      - back
    volumes:
      - "./api:/go/src/github.com/titouanfreville/popcubeapi/api"
      - "./datastores:/go/src/github.com/titouanfreville/popcubeapi/datastores"
      - "./models:/go/src/github.com/titouanfreville/popcubeapi/models"
      - "./utils:/go/src/github.com/titouanfreville/popcubeapi/utils"
    ports:
      - 8082:8080
  golint:
    build:
      context: .
      dockerfile: docker/golint.Dockerfile
    env_file: .env
    volumes:
      - "./api:/go/src/github.com/titouanfreville/popcubeapi/api"
      - "./datastores:/go/src/github.com/titouanfreville/popcubeapi/datastores"
      - "./models:/go/src/github.com/titouanfreville/popcubeapi/models"
      - "./utils:/go/src/github.com/titouanfreville/popcubeapi/utils"
  database:
    image: mariadb:10.1
    env_file: .env
    hostname: database
    ports: 
      - 3306:3306
    volumes :
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql