version: "3"
services:
  apidocumentation:
    build:
      context: .
      dockerfile: docker/slateserver.Dockerfile
    image: registry.popcube.xyz:5000/innerapi:slate-alpha-doc
    volumes:
      - "./swagger.yaml:/tmp/swagger"
    ports:
      - 4567:4567
  back:
    build:
      context: .
      dockerfile:  docker/gobase.Dockerfile
    env_file: .env
    depends_on:
      - database
    volumes:
      - "./api:/go/src/github.com/titouanfreville/popcubeapi/api"
      - "./datastores:/go/src/github.com/titouanfreville/popcubeapi/datastores"
      - "./models:/go/src/github.com/titouanfreville/popcubeapi/models"
      - "./utils:/go/src/github.com/titouanfreville/popcubeapi/utils"
      - "./configs:/go/src/github.com/titouanfreville/popcubeapi/configs"
      - "./main.go:/go/src/github.com/titouanfreville/popcubeapi/main.go"
    image: registry.popcube.xyz:5000/go:base
    ports:
      - 3000:3000
  goconvey:
    build:
      context: .
      dockerfile: docker/goconvey.Dockerfile
    env_file: .env
    depends_on:
      - back
    volumes:
      - "./api:/go/src/github.com/titouanfreville/popcubeapi/api"
      - "./datastores:/go/src/github.com/titouanfreville/popcubeapi/datastores"
      - "./models:/go/src/github.com/titouanfreville/popcubeapi/models"
      - "./utils:/go/src/github.com/titouanfreville/popcubeapi/utils"
      - "./configs:/go/src/github.com/titouanfreville/popcubeapi/configs"
      - "./main.go:/go/src/github.com/titouanfreville/popcubeapi/main.go"
    ports:
      - 8082:8080
  golint:
    build:
      context: .
      dockerfile: docker/golint.Dockerfile
    env_file: .env
    volumes:
      - "./api:/go/src/github.com/titouanfreville/popcubeapi/api"
      - "./datastores:/go/src/github.com/titouanfreville/popcubeapi/datastores"
      - "./models:/go/src/github.com/titouanfreville/popcubeapi/models"
      - "./utils:/go/src/github.com/titouanfreville/popcubeapi/utils"
      - "./configs:/go/src/github.com/titouanfreville/popcubeapi/configs"
      - "./main.go:/go/src/github.com/titouanfreville/popcubeapi/main.go"
  unit-gotest:
    build:
      context: .
      dockerfile: docker/gotest.Dockerfile
    depends_on:
      - back
      - database
    env_file: .env
  database:
    image: mariadb:10.1
    env_file: .env
    hostname: database
    ports:
      - 3306:3306
    volumes :
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/init_values.sql:/docker-entrypoint-initdb.d/init_values.sql