version: "3"
services:
  back:
    image: registry.popcube.xyz:5000/popcubeapi:latest
    env_file: .env.prod.back
    network_mode: "bridge"
    links:
      - database
    depends_on:
      - database    
  database:
    image: registry.popcube.xyz:5000/popcubedb:latest
    env_file: .env.prod
    network_mode: "bridge"
